mongodb_replication.py works only with python2
If the system uses `python3` as the default this fails with:
```
ModuleNotFoundError: No module named 'ConfigParser'
```
Because `ConfigParser` was renamed `configparser` in Python 3.